version: 1
disable_existing_loggers: true
incremental: false

formatters:
  default:
    format: '%(asctime)s   %(name)-17s   %(levelname)-8s   %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default

loggers:
  gsweb:
    handlers: [console]
    propagate: false
    level: DEBUG
  pysrvx:
    handlers: [console]
    propagate: false
    level: WARNING

root:
  handlers: [console]
  level: WARNING
